### ISSUE TITLE
ユーザー情報だけをリセットしない方法

### ISSUE THREAD

**Issue by Matthew238** [kosen-robocon-db/kosen-robocon-db#80]
DBをリセットしてしまうと、何等かの方法で保存していないユーザー情報が消えてしまうので、リセットしてもユーザー情報が維持される、またはユーザー情報以外のテーブルをドロップしidを1から始めるタスクが必要だと思っています。

**Comment by Matthew238** [comment]
タスクは実装したのでレビューをお願いします。

**Comment by mcre** [comment]
手順は下記であってますか？
``` sh
$ heroku run -a kosen-robocon-db bash
$ cd tmp
$ rails heroku:table:backup['users','kosen-robocon-db']
```

次のようなエラーが出ました。
``` sh
/app/bin/rails: No such file or directory - heroku
rails aborted!
NoMethodError: undefined method `path' for nil:NilClass
/app/lib/tasks/db.rake:19:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/app/vendor/bundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/app/bin/rails:9:in `require'
/app/bin/rails:9:in `<main>'
Tasks: TOP => heroku:table:backup
(See full trace by running task with --trace)
```

**Comment by Matthew238** [comment]
bash起動を指定しない場合はどうなりますか？

**Comment by Matthew238** [comment]
m_creさんの他所での指摘のとおり、migrate/seed後にこのコマンドで退避したusersテーブルをバックアップすると、users以外が無くなってしまうので、他の方法または改善を考えましょう。

**Comment by Matthew238** [comment]
改善してみたので、次のデプロイで試してみてください。方法はslack上の試案の4.2に書いてあります。

**Comment by Matthew238** [comment]
退避して維持する方法が手動ですが確立でき、実際に運用できているので、このissueを閉じます。
